#!/bin/bash
set -e

pkg="ncbi-blast+"

if [ "$AUTOPKGTEST_TMP" = "" ] ; then
  AUTOPKGTEST_TMP=$(mktemp -d /tmp/${pkg}-test.XXXXXX)
  trap "rm -rf $AUTOPKGTEST_TMP" 0 INT QUIT ABRT PIPE TERM
fi

cp -a /usr/share/doc/${pkg}/examples/* $AUTOPKGTEST_TMP

cd $AUTOPKGTEST_TMP
find . -name "*.gz" -exec gunzip \{\} \;

echo '---Creating Database--'
/usr/bin/makeblastdb -in testdatabase.fa -parse_seqids -dbtype nucl -out testdb
echo '---Searching Database for Hits---'
/usr/bin/blastn -query test.fa -db testdb -task blastn -dust no -outfmt "7 qseqid sseqid evalue bitscore" -max_target_seqs 2
echo '---Search and Fetch An Entry From Database---'
/usr/bin/blastdbcmd -db testdb -entry gnl1 -out test_query.fa
cat test_query.fa

echo "PASS"
